version: "3.8"
services:
  movies:
    image: chetankose/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: chetankose/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 2
  dth:
    image: chetankose/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: chetankose/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
