version: "3.8"
services:
  movies:
    image: chetankose/googlemovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 2
  train:
    image: chetankose/googletrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 2
  dth:
    image: chetankose/googledth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 2
  money:
    image: chetankose/googlemoney:latest
    ports:
      - "84:80"
    deploy:
      replicas: 2
